### ISSUE TITLE
AWS Deployment

### ISSUE THREAD

**Issue by aa1588** [aa1588/campusXchange#123]

**Comment by aa1588** [comment]
**Todo:**
- [x] Reset Password Api, Profile Page
- [x] Return Items if Qunatity > 0 from the frontend (Sudin)
- [x] Return Wishlist Items if Quantity > 0 from the frontend (Sudin)
- [ ] Reduce the Quantity of an Item from the Accepted Offer When an itemowner marks an item as sold - then populate the transaction table
- [x] Send Notifications for Questions and Answer Apis
- [ ] Send Notifications for Offer Accepted
- [x] Recommendation UI
- [x] Handle Mail Authentication Exception
- [x] Handle DataIntegrityViolationException (for ex: same phone for signup)
**Problems:**
- [x] Get wishlist Items making infinite db calls (JPA association problem) - fixed: problem was in the frontend useEffeect()

**Comment by aa1588** [comment]
Docker Compose:
-----------------
set MAIL_PASSWORD=your-mail-pass

**infra.yml**
```
---
version: "3.7"
services:
  postgres-db:
    container_name: postgres-campusxchange
    image: postgres
    environment:
      POSTGRES_DB: campusxchange
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
      PGDATA: /data/postgres
    volumes:
      - ./postgres-campusxchange:/data/postgres
    ports:
      - "5432:5432"
    restart: always
```

**app.yml**
```
services:
  campusxchange-api:
    container_name: campusxchange-api
    image: campusxchange/campusxchange-api:latest
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres-db:5432/campusxchange
      SPRING_DATASOURCE_USERNAME: admin
      SPRING_DATASOURCE_PASSWORD: password
      SPRING_MAIL_PASSWORD: lnsp qawp llmm jbzn
      ALLOWED_ORIGINS: http://localhost:3000
    ports:
      - "8080:8080"
    restart: always
    depends_on:
      - postgres-db

  campusxchange-ui:
    container_name: campusxchange-ui
    build:
      context: ./campusxchange-ui
      dockerfile: Dockerfile
    environment:
      - REACT_APP_BACKEND_URL=http://campusxchange-api:8080
    ports:
      - "3000:80" # Serve React on port 3000 through Nginx
    restart: always
    depends_on:
      - campusxchange-api

```
