### ISSUE TITLE
Dockerize Database, Backend app

### ISSUE THREAD

**Issue by aa1588** [aa1588/campusXchange#94]

**Comment by aa1588** [comment]
`   $ docker compose -f docker-compose.yml -f docker-compose-app.yml up -d
`

**Comment by aa1588** [comment]
**docker-compose.yml**
```
---
version: '3.7'
services:
  postgres-db:
    container_name: postgres-campusxchange
    image: postgres
    environment:
      POSTGRES_DB: campusxchange
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
      PGDATA: /data/postgres
    volumes:
      - ./postgres-campusxchange:/data/postgres
    ports:
      - "5432:5432"
    restart: always

```

**Comment by aa1588** [comment]
**docker-compose-app.yml**
```
version: '3.8'
services:
  campusxchange-api:
    container_name: campusxchange-api
    image: campusxchange/api-campusxchange:latest
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres-db:5432/campusxchange
      SPRING_DATASOURCE_USERNAME: admin
      SPRING_DATASOURCE_PASSWORD: password
      SPRING_MAIL_PASSWORD: ${MAIL_PASSWORD}
      ALLOWED_ORIGINS: http://localhost:3000
    ports:
      - "8080:8080"
    restart: always
    depends_on:
      - postgres-db
```
